#
###################################
# Site wide configuration
####################################
#
title: 指南针大数据团队
email: zhoushuai.njupt@gmail.com
description: A simple and awesome blog powered by jekyll.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: http://citccbd.github.io

#
###################################
# Jekyll configuration
####################################
#
highlighter:  rouge
excerpt_separator: <!--more-->

markdown: kramdown #redcarpet 
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 2..6
  enable_coderay: true

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: 指南针大数据团队
  avatar: head.jpg
  job: "A Big Data Team"
  bio: "一个关注大数据开发及应用的创新团队"
  email: zhoushuai.njupt@gmail.com
  disqus-shortname: citccbd
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: citccbd
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: zhoushuaibupt
  flickr: #username
  codepen: #username
